controller:
  config:
    body-size: "0"
    client-max-body-size: "512m"
    hsts-include-subdomains: "false"
    proxy-body-size: 512m
    proxy-buffering: "on"
    proxy-connect-timeout: "15"
    proxy-read-timeout: "600"
    proxy-send-timeout: "600"
    server-name-hash-bucket-size: "256"