# sudo

- name: Add EPEL Repository
  command: yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  become: yes
  ignore_errors: True
  when: False

- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
  become: yes
  become_user: root

- name: "Ensure Packages are installed"
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: True
    validate_certs: false
  vars:
    packages:
      - python-pip
      - rsync
      - ipvsadm
      - yum-utils
      - nc
      - net-tools
      - iptables-services
  become: yes
  become_user: root

- name: "Install pip"
  pip:
    name: pip
    version: 9.0.3
  become: yes
  become_user: root

- name: "Install setuptools"
  pip:
    name: setuptools
    version: 40.6.3
  become: yes
  become_user: root

- name: "Install openshift"
  pip:
    name: openshift
    version: 0.8
  become: yes
  become_user: root
