- name: Ensure a list of packages are installed
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: True
  vars:
    packages:
    - mailx
  become: yes
  become_user: root

- name: Copy Alert Resources
  template:
    src: alert_df.j2
    dest: /etc/cron.daily/alert_df
    mode: 0744
  become: yes
  become_user: root

- name: Copy Message Resources
  template:
    src: del_messages.j2
    dest: /etc/cron.daily/del_messages
    mode: 0744
  become: yes
  become_user: root

- name: Copy Secure Resources
  template:
    src: del_secure.j2
    dest: /etc/cron.daily/del_secure
    mode: 0744
  become: yes
  become_user: root 